export const sections = [
  {
    id: "intro",
    title: "Intro",
    steps: [
      {
        id: "reality",
        title: "Accept how dating actually works",
        instructions: [
          "Accept that dating rewards preparation. It's not luck, and things won't just 'happen'.",
          "Understand that romantic feelings are conditional. Your behaviour directly affects how someone feels about you.",
          "Once the spark drops below a certain point, it cannot be recovered. Don't burn it through bad habits.",
          "Stop obsessing over things you can't change (height, body type, etc.). Personality overwhelmingly matters more.",
          "If someone rejects you over a trivial physical trait, you've dodged a bullet.",
        ],
      },
      {
        id: "mentalhealth",
        title: "Get your mental health in order",
        instructions: [
          "Sleep 8 hours a night on a consistent schedule (same bedtime, same wake-up time).",
          "Go outside every day, even just for a short walk.",
          "Move your body daily. Any form of exercise counts.",
          "Stop using alcohol or weed as emotional substitutes.",
          "If mental health issues would affect a relationship, address them now. Seek therapy or medication before dating seriously.",
        ],
      },
      {
        id: "socialskills",
        title: "Polish your social skills",
        instructions: [
          "Say please and thank you. Treat everyone as equals (waitstaff, strangers, friends alike).",
          "Don't talk down to people or make them feel small.",
          "Be somewhat challenging. Don't make yourself instantly available or easy to read.",
          "Practice taking things to a ridiculous extreme as a go-to humour move (e.g. 'I lost count after eight hundred').",
          "Calibrate your humour to real life. Most people aren't as online as you are.",
        ],
      },
      {
        id: "confidence",
        title: "Build your confidence",
        instructions: [
          "Fake it till you make it. Everyone is insecure. Confident people just don't show it.",
          "Practice maintaining eye contact in every conversation. Nothing signals insecurity faster than looking away.",
          "Slow down physically. Keep a relaxed posture, shoulders back, no flailing.",
          "Never put yourself down in front of others. It's not self-deprecating humour. It's a universal turn-off.",
          "Actively calm yourself in stressful situations instead of letting anxiety show.",
        ],
      },
      {
        id: "appearance",
        title: "Sort your appearance",
        instructions: [
          "Shave or trim your facial hair neatly.",
          "Wash your hair and get a haircut if it's overdue.",
          "Cut and clean your nails.",
          "Dress simple but sharp. For men, a plain polo with jeans or shorts (belt and shoes matching in colour). For women, a dress or skirt with clean, elegant lines.",
          "Avoid hoodies, ripped jeans, and sports sneakers unless they're a deliberate style choice.",
        ],
      },
    ],
  },
  {
    id: "meeting",
    title: "Meeting",
    steps: [
      {
        id: "whoyouwant",
        title: "Know who you're looking for",
        instructions: [
          "Only pursue someone who is fully single. No breakups, divorces, or exes currently in the picture.",
          "Stick to a maximum of one hour travel distance between each other.",
          "Keep age gaps small. Up to 25, aim for a 2-year maximum. Above 25, a 5-year maximum.",
          "Only pursue someone you find attractive from the start. Do not date someone with 'potential' you'd need to change.",
          "Identify your personal deal breakers in advance (excessive drinking, rudeness to strangers, etc.) and treat them as absolute disqualifiers.",
          "Do not take on someone's mental health problems. They need professional help first, not you.",
        ],
      },
      {
        id: "inperson",
        title: "Meet people in real life",
        instructions: [
          "Use shared context as a conversation opener (an event, a mutual situation). Do not cold-approach random strangers on the street.",
          "Gauge interest by how engaged they are. Do they ask questions back? Do they help keep the conversation going?",
          "Keep it fun and light. Skip pickup lines and flirting techniques.",
          "Do not overshare about yourself or ask overly personal questions (address, job, age) early on.",
          "Withhold your name until they ask. If they ask, that is a positive signal of interest.",
          "Remember: if they like you, they will make it easy for you. There is no 'playing hard to get', only lack of interest.",
        ],
      },
      {
        id: "thenumber",
        title: "Ask for the number",
        instructions: [
          "Ask directly using a simple line: 'I've really enjoyed talking to you. What's your phone number?'",
          "After asking, stay silent. Let them respond. Do not fill the pause.",
          "Once you have the number, end the conversation and leave immediately.",
          "Treat anything other than a direct number as a soft rejection (an email, social media handle, or 'I don't give my number to strangers').",
          "Expect rejection often. Roughly half will decline on the spot, a few more will ghost later. That is normal.",
        ],
      },
      {
        id: "onlinedating",
        title: "Online dating",
        instructions: [
          "Use 3–4 photos: one casual, one formal, one with a pet or doing a hobby. All recent, well-lit, and showing you smiling.",
          "Keep your bio short or blank. Do not overshare personal details or flaunt wealth.",
          "Set your filters to your geographical area (max 30–40 km) and your appropriate age range.",
          "Only initiate with profiles you find genuinely attractive.",
          "Ask open-ended questions based on their photos or bio. Avoid dead-end yes/no questions.",
          "After about a dozen substantial messages, propose a coffee date. Do not chat indefinitely.",
          "If they resist meeting twice in a row, move on. They are looking for a pen pal, not a date.",
        ],
      },
    ],
  },
  {
    id: "dating",
    title: "Dating",
    steps: [
      {
        id: "thecall",
        title: "Make the date",
        instructions: [
          "Wait 4–5 days after getting their number before calling.",
          "Call on a weekday between 18:00 and 20:00. Make sure your number is not hidden.",
          "If they don't pick up, send one text: 'Hi [name], this is [your name]. Call me back on this number: [number]. Have a nice day.' Do not call again immediately.",
          "Wait 3–4 days for a callback. Try once more if no response. If still nothing, they are not interested.",
          "Keep small talk to a couple of minutes. The phone is for setting dates only.",
          "Propose a specific day, time, and location directly: 'I want to take you out. How about [day] at [time] at [place]?'",
          "If they give a scheduling conflict, offer one alternative. If they decline again without a counteroffer, wish them well and move on.",
        ],
      },
      {
        id: "planthedate",
        title: "Plan the date",
        instructions: [
          "Use a coffee date (30 minutes, café, no alcohol, host pays) if you've spoken only briefly. Use a regular date (2–3 hours, restaurant, full meal, host pays) if you already had a real first conversation.",
          "Have only one coffee date per person. The second meeting must be a proper date.",
          "For regular dates, stick to restaurants for the first 4–5 dates. Avoid cinemas, clubs, or loud places.",
          "Scout restaurants in advance. Visit alone, note the calmest tables, and reserve immediately after setting the date.",
          "Do not take the same date to the same restaurant twice in a row. Rotate through 4–5 venues.",
        ],
      },
      {
        id: "showup",
        title: "Show up right",
        instructions: [
          "Arrive 10–15 minutes early. If you will be late, text them.",
          "Wait up to 30 minutes for a late date. If no message has arrived by then, you've been stood up. Leave.",
          "Meet at the exact agreed spot, not nearby.",
          "Watch how they treat the staff. Rudeness to service personnel is a major red flag.",
          "Do not order alcohol unless they do. Limit yourself to 1–2 drinks maximum.",
          "Eat at their pace to avoid conversational dead zones.",
          "Order food you can eat cleanly.",
        ],
      },
      {
        id: "conversation",
        title: "Keep the conversation going",
        instructions: [
          "Let them do most of the talking. Ask open-ended, engaging follow-up questions.",
          "Memorise key things they mention and circle back to them later in the conversation.",
          "Do not bring up your future together (exclusivity, marriage, children) on early dates.",
          "Do not overshare about yourself. Let them dig for information.",
          "Keep some humour present but keep it clean. Avoid edgy material until you know them better.",
          "Do not brag about wealth or accomplishments. Let them discover those naturally.",
          "Steer away from heavy topics (death, illness, bad news). Keep it light and positive.",
        ],
      },
      {
        id: "endthedate",
        title: "End the date",
        instructions: [
          "End after 1.5–2 hours, ideally on a high note before things go flat.",
          "Pay the bill. Politely decline their offer to split. Tell them the host pays.",
          "If they insist hard on splitting, take note. It may signal disinterest.",
          "Escort them to their transit stop or drive them home.",
          "Say goodbye with a kiss on the mouth. Lean in, 1–2 seconds, no tongue, arms at your sides.",
          "A kiss on the cheek means they see you as a friend only. Do not ask them out again.",
          "Leave immediately after the kiss. Do not try to extend the night.",
        ],
      },
      {
        id: "betweendates",
        title: "Between dates",
        instructions: [
          "Do not contact them after the date for any reason other than setting the next one.",
          "Wait 4–5 days before calling to set the next date.",
          "If they reach out to you unprompted, use that conversation to set a date right then.",
          "Do not exhaust conversation topics over the phone. Save them for dates.",
          "Do not push for sex after the first or second date. Wait until you are exclusive (typically dates 7–10).",
          "If your date invites you in after a date, politely decline and tell them you have things tomorrow.",
        ],
      },
    ],
  },
  {
    id: "keeping",
    title: "Keeping",
    steps: [
      {
        id: "exclusive",
        title: "Become exclusive",
        instructions: [
          "Once both of you are clearly thinking about couple things (meeting parents, asking where things stand), make it official.",
          "The moment you become exclusive, stop seeing or casually contacting anyone else you were dating. No exceptions.",
        ],
      },
      {
        id: "keepdating",
        title: "Keep dating each other",
        instructions: [
          "Go on a proper date at least once every 2–3 weeks, even deep into a relationship.",
          "Do not let your presentation collapse (grooming, hygiene, dress) just because you feel comfortable together.",
          "Actively limit exposure to your most annoying habits around your partner.",
          "Communicate openly but gently when their habits bother you. Expect them to do the same.",
        ],
      },
      {
        id: "livingtogether",
        title: "Living together",
        instructions: [
          "Continue having dedicated romantic time together once every 1–2 weeks to break the daily routine.",
          "If you both work from home, give each other space by going elsewhere during part of the day.",
          "Minimise unpleasant habits around each other (bathroom habits, morning breath, hygiene products left out).",
          "Agree in advance on household responsibilities (trash, dishes, cleaning) to avoid friction.",
        ],
      },
      {
        id: "conflicts",
        title: "Handle conflicts and finances",
        instructions: [
          "Never escalate an argument. Always work toward de-escalation.",
          "Stay calm and polite. Show you have genuinely listened before restating your own position.",
          "If you reach an irresolvable impasse, agree to disagree and move on.",
          "Open a shared bank account where both contribute a fixed monthly amount.",
          "Agree on a spending threshold above which you both consult each other first.",
          "If one partner is financially irresponsible, have a direct conversation and set a monthly spending limit.",
        ],
      },
      {
        id: "warningsigns",
        title: "Spot trouble early",
        instructions: [
          "Watch for warning signs: less physical touch, emotional distance, fewer kisses, quicker irritation, less interest in sex.",
          "Do not rationalise these signs away. Act immediately.",
          "Go back to basics. Behave more like you did early in the relationship and take them on dates more often.",
          "Ask yourself: are dates still happening? Are you exposing them to too many negatives? Are arguments increasing?",
          "If it is your partner turning you off, have a calm conversation about the specific behaviours and how to reduce exposure to them.",
        ],
      },
      {
        id: "breakup",
        title: "Handle a breakup",
        instructions: [
          "If you are getting dumped, do not argue, fight, beg, or make a scene. Calmly acknowledge it.",
          "Immediately settle shared property, living arrangements, bank accounts, and subscriptions.",
          "Cut all contact permanently afterward. Do not try to return months or years later.",
          "Get back into the dating scene when you feel ready. Meeting new people is the most effective way to recover.",
          "If you are doing the dumping, use a non-arguable reason ('my feelings are just gone'). Do not list their faults.",
          "Do the breakup at their location so they do not have to travel in an emotional state. Have somewhere to go immediately afterward.",
        ],
      },
    ],
  },
];
