export const dating = {
  id: "dating",
  title: "Dating",
  color: ["#c084fc", "#f472b6"],
  cover: "images/dating.jpg",
  steps: [
    {
      id: "thecall",
      title: "Make the date",
      instructions: [
        "Wait 4–5 days after getting their number before calling.",
        "Call on a weekday, 18:00–20:00. Don't hide your number.",
        "If they don't pick up, send one text: 'Hi [name], this is [your name]. Call me back on this number: [number]. Have a nice day.' Don't call again immediately.",
        "Wait 3–4 days. Try once more. If nothing, move on.",
        "Keep small talk to a couple of minutes. The phone is for setting dates only.",
        "Propose a specific day, time, and location: 'I want to take you out. How about [day] at [time] at [place]?'",
        "If they can't make it, offer one alternative. If they decline again without suggesting another time, move on.",
      ],
    },
    {
      id: "planthedate",
      title: "Plan the date",
      instructions: [
        "Coffee date (30 min, café, no alcohol) for brief first meetings. Proper date (2–3 hours, restaurant, full meal) if you've already had a real conversation.",
        "Only one coffee date per person. The second meeting must be a proper date.",
        "Stick to restaurants for the first 4–5 dates. Avoid cinemas, clubs, loud places.",
        "Scout restaurants in advance. Visit alone, find the quietest tables, and book right after confirming the date.",
        "Don't repeat the same restaurant back to back. Rotate through 4–5 venues.",
      ],
    },
    {
      id: "showup",
      title: "Show up right",
      instructions: [
        "Arrive 10–15 minutes early. Text if you'll be late.",
        "Wait up to 30 minutes. No message by then means you've been stood up. Leave.",
        "Meet at the exact agreed spot, not nearby.",
        "Watch how they treat the staff. Rudeness is a major red flag.",
        "Don't order alcohol unless they do. Max 1–2 drinks.",
        "Eat at their pace to avoid conversational dead zones.",
        "Order food you can eat cleanly.",
      ],
    },
    {
      id: "conversation",
      title: "Keep the conversation going",
      instructions: [
        "Let them do most of the talking. Ask open-ended follow-up questions.",
        "Remember what they mention and circle back to it later.",
        "Don't bring up your future together on early dates.",
        "Do not overshare about yourself. Let them dig for information.",
        "Keep humour present but clean. Avoid edgy material until you know them.",
        "Don't brag. Let them discover what you're about naturally.",
        "Steer clear of heavy topics. Keep it light.",
      ],
    },
    {
      id: "endthedate",
      title: "End the date",
      instructions: [
        "End after 1.5–2 hours, ideally on a high note before things go flat.",
        "Pay the bill. If they offer to split, decline politely.",
        "If they insist hard on splitting, take note. It may signal disinterest.",
        "Escort them to their transit stop or drive them home.",
        "Say goodbye with a kiss on the mouth. Lean in, 1–2 seconds, no tongue, arms at your sides.",
        "A kiss on the cheek means they see you as a friend only. Do not ask them out again.",
        "Leave immediately after the kiss. Do not try to extend the night.",
      ],
    },
    {
      id: "betweendates",
      title: "Between dates",
      instructions: [
        "Only reach out to set the next date. Nothing else.",
        "Wait 4–5 days before calling to set the next date.",
        "If they reach out, use it to set a date.",
        "Do not exhaust conversation topics over the phone. Save them for dates.",
        "Don't push for sex early. Wait until you're exclusive (around dates 7–10).",
        "If they invite you in, decline politely. Say you have things tomorrow.",
      ],
    },
  ],
};
